package sergisa.orderbuilder.ui;

import com.intellij.uiDesigner.core.GridConstraints;
import com.intellij.uiDesigner.core.GridLayoutManager;
import sergisa.orderbuilder.PrinterRepository;
import sergisa.orderbuilder.TableWriter;
import sergisa.orderbuilder.model.OrderItem;
import sergisa.orderbuilder.model.OrderList;
import sergisa.orderbuilder.model.Printer;
import sergisa.orderbuilder.ui.list.PrinterListViewItemRenderer;

import javax.swing.*;
import javax.swing.plaf.FontUIResource;
import javax.swing.text.StyleContext;
import java.awt.*;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.io.File;
import java.util.Locale;

public class OrderBuilderForm extends JFrame {
    private JList<Printer> printerListView;
    private JButton refreshButton;
    private JPanel root;
    private JEditorPane orderEditorView;
    private JButton documentEditButton;
    private JButton printerRepositoryEditButton;
    PrinterRepository printerRepository;
    JMenu mainMenu;
    JMenuBar menuBar;

    public OrderBuilderForm(PrinterRepository printerRepository) {
        setTitle("Order Builder");
        setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        setSize(800, 400);
        //createMenu();
        try {
            File fontFile = new File(getClass().getResource("Raleway-Light.ttf").getFile());
            Font customFont = Font.createFont(Font.TRUETYPE_FONT, fontFile).deriveFont(12f);
            GraphicsEnvironment ge = GraphicsEnvironment.getLocalGraphicsEnvironment();
            ge.registerFont(customFont);
            setFont(customFont);
            refreshButton.setFont(customFont);
        } catch (Exception e) {
            System.out.println(e.getMessage());
        }
        setVisible(true);
        setContentPane(root);
        this.printerRepository = printerRepository;
        DefaultListModel<Printer> printerListModel = new DefaultListModel<>();
        printerListView.setModel(printerListModel);
        printerListView.setSelectionMode(ListSelectionModel.MULTIPLE_INTERVAL_SELECTION);

        printerRepository.getPrinters().forEach(printerListModel::addElement);
        printerListView.setCellRenderer(new PrinterListViewItemRenderer());
        refreshButton.addActionListener(e -> {
            OrderList orderList = buildOrder();
            File file = new File("src/orderTemplate.docx");
            TableWriter writer = new TableWriter(file, orderList);
        });
        documentEditButton.addActionListener(e -> {
            openDocumentRequisitesEditForm();
        });
        printerRepositoryEditButton.addActionListener(e -> {
            openEditRepositoryForm(printerRepository);
        });
    }

    private void createMenu() {
        menuBar = new JMenuBar();
        mainMenu = new JMenu("Управление");
        mainMenu.add(createMenuItem("Редактировать принтеры", "E", new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                openEditRepositoryForm(printerRepository);
            }
        }));
        mainMenu.add(createMenuItem("Настроить реквизиты документа", new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                openDocumentRequisitesEditForm();
            }
        }));
        menuBar.add(mainMenu);
        setJMenuBar(menuBar);
    }

    private void openDocumentRequisitesEditForm() {
        RequisitesEditForm requisitesEditForm = new RequisitesEditForm();
        requisitesEditForm.setLocationRelativeTo(this);
    }

    public OrderList buildOrder() {
        OrderList orderList = new OrderList();
        printerListView.getSelectedValuesList().forEach(printer -> {
            orderList.addOrderItem(new OrderItem().setPrinter(printer));
        });
        orderList.setAddress("Открытое шоссе, д. 24, стр. 27, каб. №319").setContactPerson("Исаков С.С.");
        return orderList;
    }

    private void openEditRepositoryForm(PrinterRepository printerRepository) {
        RepositoryEditorForm repositoryEditorForm = new RepositoryEditorForm(printerRepository);
        repositoryEditorForm.setLocation(getX() + getWidth(), getY());
    }

    private JMenuItem createMenuItem(String name, ActionListener listener) {
        return createMenuItem(name, null, listener);
    }

    private JMenuItem createMenuItem(String name, String shortcut, ActionListener listener) {
        //mainMenu.setMnemonic(shortcut.charAt(0));
        JMenuItem item = new JMenuItem(name);
        //item.setMnemonic(shortcut.charAt(0)); // русская буква
        if (shortcut != null) item.setAccelerator(KeyStroke.getKeyStroke(shortcut.charAt(0)));
        item.addActionListener(listener);
        return item;
    }

    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        root = new JPanel();
        root.setLayout(new GridLayoutManager(4, 2, new Insets(10, 10, 10, 10), -1, -1));
        final JSplitPane splitPane1 = new JSplitPane();
        root.add(splitPane1, new GridConstraints(3, 0, 1, 2, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_BOTH, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_WANT_GROW, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, null, new Dimension(200, 200), null, 0, false));
        final JScrollPane scrollPane1 = new JScrollPane();
        splitPane1.setLeftComponent(scrollPane1);
        printerListView = new JList();
        scrollPane1.setViewportView(printerListView);
        orderEditorView = new JEditorPane();
        splitPane1.setRightComponent(orderEditorView);
        refreshButton = new JButton();
        Font refreshButtonFont = this.$$$getFont$$$("Raleway Light", -1, -1, refreshButton.getFont());
        if (refreshButtonFont != null) refreshButton.setFont(refreshButtonFont);
        refreshButton.setText("Сформировать");
        root.add(refreshButton, new GridConstraints(2, 1, 1, 1, GridConstraints.ANCHOR_EAST, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 1, false));
        final JLabel label1 = new JLabel();
        Font label1Font = this.$$$getFont$$$("Nunito ExtraBold", -1, 16, label1.getFont());
        if (label1Font != null) label1.setFont(label1Font);
        label1.setText("Формирование заявки");
        root.add(label1, new GridConstraints(0, 0, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        final JToolBar toolBar1 = new JToolBar();
        root.add(toolBar1, new GridConstraints(1, 0, 1, 2, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_WANT_GROW, GridConstraints.SIZEPOLICY_FIXED, null, new Dimension(-1, 20), null, 0, false));
        documentEditButton = new JButton();
        documentEditButton.setForeground(new Color(-16756777));
        documentEditButton.setText("Редактировать шаблон документа");
        toolBar1.add(documentEditButton);
        printerRepositoryEditButton = new JButton();
        printerRepositoryEditButton.setForeground(new Color(-16756777));
        printerRepositoryEditButton.setText("Принтеры");
        toolBar1.add(printerRepositoryEditButton);
    }

    /**
     * @noinspection ALL
     */
    private Font $$$getFont$$$(String fontName, int style, int size, Font currentFont) {
        if (currentFont == null) return null;
        String resultName;
        if (fontName == null) {
            resultName = currentFont.getName();
        } else {
            Font testFont = new Font(fontName, Font.PLAIN, 10);
            if (testFont.canDisplay('a') && testFont.canDisplay('1')) {
                resultName = fontName;
            } else {
                resultName = currentFont.getName();
            }
        }
        Font font = new Font(resultName, style >= 0 ? style : currentFont.getStyle(), size >= 0 ? size : currentFont.getSize());
        boolean isMac = System.getProperty("os.name", "").toLowerCase(Locale.ENGLISH).startsWith("mac");
        Font fontWithFallback = isMac ? new Font(font.getFamily(), font.getStyle(), font.getSize()) : new StyleContext().getFont(font.getFamily(), font.getStyle(), font.getSize());
        return fontWithFallback instanceof FontUIResource ? fontWithFallback : new FontUIResource(fontWithFallback);
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return root;
    }

}
