package sergisa.orderbuilder.ui;

import com.intellij.uiDesigner.core.GridConstraints;
import com.intellij.uiDesigner.core.GridLayoutManager;
import sergisa.orderbuilder.PrinterRepository;
import sergisa.orderbuilder.TableWriter;
import sergisa.orderbuilder.model.OrderItem;
import sergisa.orderbuilder.model.OrderList;
import sergisa.orderbuilder.model.Printer;
import sergisa.orderbuilder.ui.list.PrinterListViewItemRenderer;

import javax.swing.*;
import javax.swing.plaf.FontUIResource;
import javax.swing.text.StyleContext;
import java.awt.*;
import java.io.File;
import java.util.Locale;

public class OrderBuilderForm extends JFrame {
    private JList<Printer> printerListView;
    private JButton refreshButton;
    private JPanel root;
    private JEditorPane orderEditorView;
    private JButton repositoryEditButton;
    private JTextField significantFIOTextField;
    private JTextField significantPostTextField;
    PrinterRepository printerRepository;

    public OrderBuilderForm(PrinterRepository printerRepository) {
        setTitle("Order Builder");
        setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        setSize(800, 400);
        try {
            File fontFile = new File(getClass().getResource("Raleway-Light.ttf").getFile());
            Font customFont = Font.createFont(Font.TRUETYPE_FONT, fontFile).deriveFont(12f);
            GraphicsEnvironment ge = GraphicsEnvironment.getLocalGraphicsEnvironment();
            ge.registerFont(customFont);
            setFont(customFont);
            refreshButton.setFont(customFont);
        } catch (Exception e) {
            System.out.println(e.getMessage());
        }
        setVisible(true);
        setContentPane(root);
        this.printerRepository = printerRepository;
        DefaultListModel<Printer> printerListModel = new DefaultListModel<>();
        printerListView.setModel(printerListModel);
        printerListView.setSelectionMode(ListSelectionModel.MULTIPLE_INTERVAL_SELECTION);

        printerRepository.getPrinters().forEach(printerListModel::addElement);
        printerListView.setCellRenderer(new PrinterListViewItemRenderer());
        repositoryEditButton.addActionListener(e -> {
            openEditRepositoryForm(printerRepository);
        });
        refreshButton.addActionListener(e -> {
            OrderList orderList = buildOrder();
            File file = new File("src/orderTemplate.docx");
            TableWriter writer = new TableWriter(file, orderList);
        });
    }

    public OrderList buildOrder() {
        OrderList orderList = new OrderList();
        printerListView.getSelectedValuesList().forEach(printer -> {
            orderList.addOrderItem(new OrderItem().setPrinter(printer));
        });
        orderList.setAddress("Открытое шоссе, д. 24, стр. 27, каб. №319").setContactPerson("Исаков С.С.");
        return orderList;
    }

    private void openEditRepositoryForm(PrinterRepository printerRepository) {
        RepositoryEditorForm repositoryEditorForm = new RepositoryEditorForm(printerRepository);
        repositoryEditorForm.setLocation(getX() + getWidth(), getY());
    }

    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        root = new JPanel();
        root.setLayout(new GridLayoutManager(5, 3, new Insets(10, 10, 10, 10), -1, -1));
        final JSplitPane splitPane1 = new JSplitPane();
        root.add(splitPane1, new GridConstraints(2, 0, 1, 3, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_BOTH, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_WANT_GROW, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, null, new Dimension(200, 200), null, 0, false));
        final JScrollPane scrollPane1 = new JScrollPane();
        splitPane1.setLeftComponent(scrollPane1);
        printerListView = new JList();
        scrollPane1.setViewportView(printerListView);
        orderEditorView = new JEditorPane();
        splitPane1.setRightComponent(orderEditorView);
        refreshButton = new JButton();
        Font refreshButtonFont = this.$$$getFont$$$("Raleway Light", -1, -1, refreshButton.getFont());
        if (refreshButtonFont != null) refreshButton.setFont(refreshButtonFont);
        refreshButton.setText("Сформировать");
        root.add(refreshButton, new GridConstraints(1, 2, 1, 1, GridConstraints.ANCHOR_EAST, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 1, false));
        repositoryEditButton = new JButton();
        Font repositoryEditButtonFont = this.$$$getFont$$$("Raleway Light", -1, -1, repositoryEditButton.getFont());
        if (repositoryEditButtonFont != null) repositoryEditButton.setFont(repositoryEditButtonFont);
        repositoryEditButton.setText("Редактировать репозиторий");
        root.add(repositoryEditButton, new GridConstraints(1, 0, 1, 2, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        final JLabel label1 = new JLabel();
        label1.setText("Визирующее лицо");
        root.add(label1, new GridConstraints(3, 0, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        final JLabel label2 = new JLabel();
        label2.setText("Должность визирующего");
        root.add(label2, new GridConstraints(4, 0, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        significantPostTextField = new JTextField();
        significantPostTextField.setText("Декан факультета «Информационные технологии»");
        root.add(significantPostTextField, new GridConstraints(4, 1, 1, 2, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_WANT_GROW, GridConstraints.SIZEPOLICY_FIXED, null, new Dimension(150, -1), null, 0, false));
        significantFIOTextField = new JTextField();
        significantFIOTextField.setHorizontalAlignment(2);
        significantFIOTextField.setText("Л.С. Куравский");
        root.add(significantFIOTextField, new GridConstraints(3, 1, 1, 2, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_WANT_GROW, GridConstraints.SIZEPOLICY_FIXED, null, new Dimension(150, -1), null, 0, false));
        final JLabel label3 = new JLabel();
        label3.setText("Label");
        root.add(label3, new GridConstraints(0, 0, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
    }

    /**
     * @noinspection ALL
     */
    private Font $$$getFont$$$(String fontName, int style, int size, Font currentFont) {
        if (currentFont == null) return null;
        String resultName;
        if (fontName == null) {
            resultName = currentFont.getName();
        } else {
            Font testFont = new Font(fontName, Font.PLAIN, 10);
            if (testFont.canDisplay('a') && testFont.canDisplay('1')) {
                resultName = fontName;
            } else {
                resultName = currentFont.getName();
            }
        }
        Font font = new Font(resultName, style >= 0 ? style : currentFont.getStyle(), size >= 0 ? size : currentFont.getSize());
        boolean isMac = System.getProperty("os.name", "").toLowerCase(Locale.ENGLISH).startsWith("mac");
        Font fontWithFallback = isMac ? new Font(font.getFamily(), font.getStyle(), font.getSize()) : new StyleContext().getFont(font.getFamily(), font.getStyle(), font.getSize());
        return fontWithFallback instanceof FontUIResource ? fontWithFallback : new FontUIResource(fontWithFallback);
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return root;
    }
}
